### ISSUE TITLE
Premint SDK uses `Address` instead of `Account` for `signTypedData` input, which results in error when signing

### ISSUE THREAD

**Issue by stephancill** [ourzora/zora-protocol#398]
## Error & Repro

I have the following setup for creating premints on behalf of another account:

```typescript
const adminAccount = privateKeyToAccount(
  process.env.ZORA_ADMIN_PRIVATE_KEY as `0x${string}`
);

const contractAdminWallet = createWalletClient({
  chain: zora,
  account: adminAccount,
  transport: http(),
});

const premintClient = createPremintClient({
  chain: zora,
});

const collection = {
  contractAdmin: adminAccount.address,
  contractName: title,
  // Collection metadata same as token metadata
  contractURI: tokenMetadataURI,
};

const premint = await premintClient.createPremint({
  premintConfigVersion: PremintConfigVersion.V2,
  checkSignature: true,
  collection,
  creatorAccount: contractAdminWallet.account.address,
  walletClient: contractAdminWallet,
  tokenCreationConfig: {
    tokenURI: tokenMetadataURI,
    payoutRecipient: creator.address,
    // TODO: createReferral: mod creator address,
  },
});
```

On submit, I get a viem error:
```
...
api:dev:     shortMessage: 'RPC Request failed.',
api:dev:     version: 'viem@1.20.0',
api:dev:     cause: {
api:dev:       code: -32601,
api:dev:       message: 'the method eth_signTypedData_v4 does not exist/is not available'
api:dev:     },
```

## What's wrong

When you pass a string instead of an `Account` to the `account` parameter of viem's `walletClient.signTypedData`, it falls back to being constructed as JSON RPC `Account` object rather than the more appropriate local account type, which is the condition for the signature to work with local accounts as mentioned in the [docs](https://viem.sh/docs/actions/wallet/signTypedData.html#json-rpc-methods):
<img width="436" alt="Screenshot 2024-01-11 at 19 51 23" src="https://github.com/ourzora/zora-protocol/assets/5469870/178964d3-6b59-445a-83d5-7d7aca8f4d63">

## Solution

The solution is to explicitly pass the full `Account` object to the `walletClient.signTypedData` call here: https://github.com/ourzora/zora-protocol/blob/main/packages/protocol-sdk/src/premint/premint-client.ts#L669C10-L676

One way of doing that (which is potentially also the most flexible) would most likely be to accept an `Account | Address` here: https://github.com/ourzora/zora-protocol/blob/main/packages/protocol-sdk/src/premint/premint-client.ts#L328 and handle the differences downstream.

Let me know if I can provide more info

**Comment by corbinpage** [comment]
So am I. When will this be resolved? 😢

**Comment by stephancill** [comment]
@jellohouse @corbinpage this patch is what fixed it for our use case (we're only using local accounts). might be of use to you https://github.com/mod-protocol/mod/blob/main/patches/%40zoralabs%2Bprotocol-sdk%2B0.5.0.patch

**Comment by jellohouse** [comment]
Ok thanks - yes that works for now :)

**Comment by iainnash** [comment]
Hey! We've totally missed this and can integrate a fix soon.

**Comment by iainnash** [comment]
Fixed with https://www.npmjs.com/package/@zoralabs/protocol-sdk/v/0.5.3
