### ISSUE TITLE
where i can bridge my zora eth to arbitrum other than official one?

### ISSUE THREAD

**Issue by Nar035** [ourzora/zora-protocol#400]

**Comment by iainnash** [comment]
Have you seen the "Instant Bridge" on https://bridge.zora.energy/?

**Comment by iainnash** [comment]
There also are a few third party bridges:

* https://orbiter.finance Orbiter
* https://relay.link/bridge/ethereum/ Relay (Reservoir)

However these are unofficial bridges and you should do your own research how they work and avoid transacting with large amounts (> 0.5 / 1 eth) with them for the time being.
