### ISSUE TITLE
Total amount of Nfts minted issue

### ISSUE THREAD

**Issue by AnonVee1** [ourzora/zora-protocol#401]
When changing the network on our zora profile, the total nfts minted shows for all chains and not for the particular network selected.
![image](https://github.com/ourzora/zora-protocol/assets/142122008/cb493656-3ee6-4cdc-8493-82568c90249c)

You need to add a code that displays
Total nfts minted on "network" is :

**Comment by iainnash** [comment]
Passed along to the team.
