### ISSUE TITLE
Arrange Nfts in a better way

### ISSUE THREAD

**Issue by AnonVee1** [ourzora/zora-protocol#402]
If anyone mints 2+ nfts from a particular creator,
there should be a sub-collection folder in our profile that contains all the nfts you minted from that creator.

This will help us better organize our nfts and also reduce the stress of looking through all nfts on our profile or the blockchain scan for the nfts you minted from a particular creator.

You can also create a feature enabling us to create "personal" folders on our profile.
This is very useful in the sense that we may have some important nfts and we want to put them in a place where we can easily find them.

**Comment by iainnash** [comment]
Passed along to the product team.
