### ISSUE TITLE
Arbitrum Subgraph

### ISSUE THREAD

**Issue by jonathandiep** [ourzora/zora-protocol#405]
Curious if Zora is going to index Arbitrum? 

https://github.com/ourzora/zora-protocol/blob/e9fb5072112b4434cc649c95729f4bd8c6d5e0d0/packages/protocol-sdk/src/apis/chain-constants.ts#L29-L100

Would appreciate since we are using the protocol-sdk to grab mint fee data (following from https://github.com/ourzora/zora-protocol/issues/403)

**Comment by iainnash** [comment]
We can add it for you!

**Comment by iainnash** [comment]
Added :).

**Comment by jonathandiep** [comment]
@iainnash Appreciate getting this in! We're still on [0.5.6-exports.0](https://www.npmjs.com/package/@zoralabs/protocol-sdk/v/0.5.6-exports.0) and I was wondering if there is going to be a new version that will include the arbitrum fix here?

**Comment by iainnash** [comment]
Package should be deployed very soon.

**Comment by iainnash** [comment]
Package has been deployed.
