### ISSUE TITLE
Zora Protocol - Base Sepolia Deployments

### ISSUE THREAD

**Issue by SweetmanTech** [ourzora/zora-protocol#408]
Hi Zora,

it's me again
can you please deploy your wonderful protocol on `base-sepolia`?
we builders on base like zora
help zora be more based
chain details below

https://docs.base.org/network-information/

<img width="535" alt="Screenshot 2024-03-25 at 7 22 51 PM" src="https://github.com/ourzora/zora-protocol/assets/23249402/8bf9f33f-e3ff-4cd8-93ee-f2b95f7e75b0">

### delivery
- `packages/1155-deployments/addresses` - add `84532.json`
- include `"FACTORY_PROXY": "0x777777C338d93e2C7adf08D102d45CA7CC4Ed021",` (if deterministic deployment is possible)

<img width="1102" alt="Screenshot 2024-03-25 at 7 23 38 PM" src="https://github.com/ourzora/zora-protocol/assets/23249402/ea4a12f8-1036-430a-8eea-cb1dc5cd1088">

**Comment by iainnash** [comment]
We’re planning on it very soon. 

We deployed goerli base but haven’t deployed sepolia base yet.

**Comment by kulkarohan** [comment]
hey @SweetmanTech you can use `"FACTORY_PROXY": "0x8cfbF874A12b346115003532119C29f6B56719CB"` for base sepolia

**Comment by techeng322** [comment]
Hi, @kulkarohan 
could you please let me know the FIXED_PRICE_SALE_STRATEGY address also?
regards. 🙏

**Comment by kulkarohan** [comment]
yep! "FIXED_PRICE_SALE_STRATEGY": "0xd34872BE0cdb6b09d45FCa067B07f04a1A9aE1aE"

we'll update the package soon with a 84532.json

**Comment by iainnash** [comment]
All updated.
