### ISSUE TITLE
'Dynamic require of "punycode" is not supported' when I import zora protocol sdk

### ISSUE THREAD

**Issue by boosik-riverbank** [ourzora/zora-protocol#412]
Hi, I am boosik developing with zora protocol sdk + nextjs for minting my NFT in frontend.
I got these error when I import zora protocol-sdk.
I am trying zora protocol-sdk + Viem, below is my code-base.
```
import {createMintClient} from "@zoralabs/protocol-sdk";
...
const mintClient = createMintClient({ chain: walletClient.chain! })
```

And I got this error in browser,

```
Uncaught Error: Dynamic require of "punycode" is not supported
    at eval (index.js:105:9)
    at ../../node_modules/whatwg-url/lib/url-state-machine.js (index.js:486:20)
    at __require2 (index.js:111:50)
    at ../../node_modules/whatwg-url/lib/URL-impl.js (index.js:1558:15)
    at __require2 (index.js:111:50)
    at ../../node_modules/whatwg-url/lib/URL.js (index.js:1717:16)
    at __require2 (index.js:111:50)
    at ../../node_modules/whatwg-url/lib/public-api.js (index.js:1898:19)
    at __require2 (index.js:111:50)
```

Is there any tip for handling this error?

**Comment by intergalacticspacehighway** [comment]
@iainnash seems same issue here. the punnycode import gets added in dist folder of protocol-sdk. `node_modules/@zoralabs/protocol-sdk/dist/index.js:395:9`. Looks like maybe an issue with bundling setup?

<img width="1112" alt="Screenshot 2024-05-16 at 12 32 13 PM" src="https://github.com/ourzora/zora-protocol/assets/23293248/aea1f915-538f-4eff-aa6c-2deec3b8552f">

**Comment by intergalacticspacehighway** [comment]
Some findings. `var CrossFetch = __toESM(require_node_ponyfill(), 1);` is getting injected in the dist/index.js of @zoralabs/protocol-sdk's distribution bundle, probably due to graphql-request, this requires the punycode. Ideally this should not be a part of protocol-sdk's bundle, but i suspect some build script issues.

**Comment by iainnash** [comment]
Hi,

This has been fixed, `graphql-request` has been removed as a dep.

Feel free to re-open if this arises again.
