### ISSUE TITLE
Is it possible to provide gasless onchain experience for users?

### ISSUE THREAD

**Issue by abogacki** [ourzora/zora-protocol#427]
In my project I'd like to use Zora NFT protocol (ideally through the protocol sdk) to create ERC1155 collections and tokens within it. I was wandering if there's a way to create 1155 on-chain with a gasless experience (i.e. I'm paying the gas fee for the users, but they are the owners of their collections).
Our use case is that we'd also enable users with possibility to mint from our platform using cross-chain transactions ([decent.xyz](http://decent.xyz/), [layerzero.network](http://layerzero.network/)). Such transactions require the contract to exist on chain, but we'd still like to provide gasless experience to some of our users. Can this be achieved?

**Comment by iainnash** [comment]
We have gasless flows available via our sdk at https://docs.zora.co/protocol-sdk/creator/premint which can then be propagated using decent/layerzero at a later time. Is that what you're looking for?

**Comment by iainnash** [comment]
Also, if you wish to pay the gas fee for other users operations with smart wallets this should be no problem with our current onchain infrastructure.

I'm closing this issue for now and you can reopen with further questions or make a new issue.
