### ISSUE TITLE
Base - mintWithRewards

### ISSUE THREAD

**Issue by SweetmanTech** [ourzora/zora-protocol#432]
Can you please update the deployment on `base` to include the `mintWithRewards` method?

example contract: https://basescan.org/address/0x5c0fd2ceb2fb1799116514d29b9956097eaa8c87
- deployed `Aug-05-2024` using the Zora UI

missing the `mintWithRewards` method
![Screenshot 2024-08-06 at 10 47 13 AM](https://github.com/user-attachments/assets/be7c8707-3deb-45dc-8cb1-189806f4947f)

**Comment by IsabellaSmallcombe** [comment]
Hi @SweetmanTech. `mintWithRewards` is deprecated we recommend using `mint`

**Comment by kulkarohan** [comment]
yup ^ we consolidated those two functions.

the `mint` function supports a `rewardsRecipients` array.

```
    /// @notice Mint tokens and payout rewards given a minter contract, minter arguments, and rewards arguments
    /// @param minter The minter contract to use
    /// @param tokenId The token ID to mint
    /// @param quantity The quantity of tokens to mint
    /// @param rewardsRecipients The addresses of rewards arguments - rewardsRecipients[0] = mintReferral, rewardsRecipients[1] = platformReferral
    /// @param minterArguments The arguments to pass to the minter
    function mint(
        IMinter1155 minter,
        uint256 tokenId,
        uint256 quantity,
        address[] calldata rewardsRecipients,
        bytes calldata minterArguments
    ) external payable nonReentrant
```
