### ISSUE TITLE
The network does not display the network correctly when switching networks.

### ISSUE THREAD

**Issue by doscow1** [ourzora/zora-protocol#441]
https://github.com/user-attachments/assets/84d2d832-f0e9-4185-b672-c076d29eab4e

On the https://zora.co/offers page, when switching networks, it shows a different network than the one in which the nfts are located. For example, it shows the Zora network, but the nfts are from the Ethereum network. More details on the attached video.

**Comment by iainnash** [comment]
We've deprecated this feature. Thanks for the report!
